// sample-app-vue/src/App.vue
<script setup lang="ts">
import DemoPage from "@/pages/DemoPage.vue";
import logo from "./assets/vue.svg";
</script>

<template>
  <main>
    <header class="header">
      <div class="header-link">
        <img :src="logo" alt="logo" class="logo" />
        <h1>SAMPLE APP VUE</h1>
      </div>
    </header>
    <DemoPage />
  </main>
</template>

// sample-app-react/src/App.tsx
import "@/App.css";
import logo from "@/assets/react.svg";
import DemoPage from "@/pages/DemoPage";

const App = () => {
  return (
    <main>
      <header className="header">
        <div className="header-link">
          <img src={logo} alt="logo" className="logo" />
          <h1>SAMPLE APP REACT</h1>
        </div>
      </header>
      <DemoPage />
    </main>
  );
};

export default App;
